#! /bin/sh

go build

num_pats=(100000 10000 1000 100 10)

num_lines=(10 100 1000 10000)

for lines in "${num_lines[@]}"; do
    for pats in "${num_pats[@]}"; do
        echo "PATTERNS: $pats | LINES: $lines"
        echo "\n>>> grep -F"
        time grep -F -f pats-${pats}.txt lines-${lines}.txt -c
        echo "\n>>> rg -F"
        time rg -F -f pats-${pats}.txt lines-${lines}.txt -c
        echo "\n>>> biblio"
        time ./cmd -patternsFile pats-${pats}.txt -file lines-${lines}.txt
        echo "-----------"
    done
    echo "===================="
    echo "===================="
done
