#! /bin/sh

num_pats=(100000 10000 1000 100 10)

num_lines=(10 100 1000 10000)


for lines in "${num_lines[@]}"; do
    cat ../war-and-peace.txt | gshuf -n ${lines} | tr '[:upper:]' '[:lower:]' > lines-${lines}.txt
done
for pats in "${num_pats[@]}"; do
    cat ../words.txt | gshuf -n ${pats} | tr '[:upper:]' '[:lower:]' > pats-${pats}.txt
done
